# Generated by Django 4.2.3 on 2023-07-10 03:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormAList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_f', models.TextField(blank=True, default='', null=True)),
                ('a_f', models.TextField(blank=True, default='', null=True)),
                ('c_f', models.TextField(blank=True, default='', null=True)),
                ('d_f', models.TextField(blank=True, default='', null=True)),
                ('e_f', models.TextField(blank=True, default='', null=True)),
                ('f_f', models.TextField(blank=True, default='', null=True)),
                ('g_f', models.TextField(blank=True, default='', null=True)),
                ('h_f', models.TextField(blank=True, default='', null=True)),
                ('i_f', models.TextField(blank=True, default='', null=True)),
                ('j_f', models.TextField(blank=True, default='', null=True)),
                ('k_f', models.TextField(blank=True, default='', null=True)),
                ('l_f', models.TextField(blank=True, default='', null=True)),
                ('m_f', models.TextField(blank=True, default='', null=True)),
                ('n_f', models.TextField(blank=True, default='', null=True)),
                ('o_f', models.TextField(blank=True, default='', null=True)),
                ('p_f', models.TextField(blank=True, default='', null=True)),
                ('q_f', models.TextField(blank=True, default='', null=True)),
                ('r_f', models.TextField(blank=True, default='', null=True)),
                ('s_f', models.TextField(blank=True, default='', null=True)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新時間')),
            ],
            options={
                'db_table': 'form_alist',
            },
        ),
        migrations.CreateModel(
            name='FormBList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_f', models.TextField(blank=True, default='', null=True)),
                ('b_f', models.TextField(blank=True, default='', null=True)),
                ('c_f', models.TextField(blank=True, default='', null=True)),
                ('d_f', models.TextField(blank=True, default='', null=True)),
                ('e_f', models.TextField(blank=True, default='', null=True)),
                ('f_f', models.TextField(blank=True, default='', null=True)),
                ('g_f', models.TextField(blank=True, default='', null=True)),
                ('h_f', models.TextField(blank=True, default='', null=True)),
                ('i_f', models.TextField(blank=True, default='', null=True)),
                ('j_f', models.TextField(blank=True, default='', null=True)),
                ('k_f', models.TextField(blank=True, default='', null=True)),
                ('l_f', models.TextField(blank=True, default='', null=True)),
                ('m_f', models.TextField(blank=True, default='', null=True)),
                ('n_f', models.TextField(blank=True, default='', null=True)),
                ('o_f', models.TextField(blank=True, default='', null=True)),
                ('p_f', models.TextField(blank=True, default='', null=True)),
                ('q_f', models.TextField(blank=True, default='', null=True)),
                ('r_f', models.TextField(blank=True, default='', null=True)),
                ('s_f', models.TextField(blank=True, default='', null=True)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新時間')),
            ],
            options={
                'db_table': 'form_blist',
            },
        ),
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='原名稱')),
                ('new_name', models.TextField(default='', null=True, verbose_name='欄位名稱')),
                ('hide', models.CharField(default='', max_length=5, null=True, verbose_name='隱藏欄位')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 7, 10, 3, 29, 54, 933317), verbose_name='建立日期')),
            ],
            options={
                'db_table': 'form_fields',
            },
        ),
    ]
